import os

ASTRA_DB_API_ENDPOINT = os.getenv("ASTRA_DB_API_ENDPOINT")
ASTRA_DB_APPLICATION_TOKEN = os.getenv("ASTRA_DB_APPLICATION_TOKEN")
ASTRA_DB_KEYSPACE = os.getenv("ASTRA_DB_KEYSPACE", "default_keyspace")

OLLAMA_MODEL = "llama3"
EMBEDDING_MODEL = "nomic-embed-text"

MAX_CRAWL_PAGES = 10
CHUNK_SIZE = 5000
CHUNK_OVERLAP = 200